name: NotInDocTest

on:
  push:
    branchs:
    - actions
    paths-ignore:
    - 'doc/**'

jobs:
  NonDocsChange:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Echo Stuff
      run: |
        echo "Not in docs"
